import{distanceMeters,formatDistance,initialSession,completeCurrent,skipCurrent,beginReturn,activeStage,scheduleLabel,createMapModel,navigationSnapshot,initialAudioGuidanceState,navigationAudioDecision,minutesUntilDeadline,AUDIO_PRIORITY,initialSpeechQueueState,enqueueSpeech,completeSpeech}from"./core.js";
import{initialReadinessState,readinessSummary,recoveryStatus,permissionStatus,storageStatus,installationInstructions,canStartFieldSession}from"./readiness.js";
const $=id=>document.getElementById(id);let project,manifest,session,watchId=null,lastPosition=null,lastStageDistance=null,awaySamples=0,audioGuidanceState=initialAudioGuidanceState(),audioGuidanceEnabled=true,speechQueueState=initialSpeechQueueState(),speechInProgress=false,readinessState=initialReadinessState(),deferredInstallPrompt=null,recoveryCandidate=null,fieldReadinessOverride=false;const STORE="malbork-2026-session-v1";const SVG_NS="http://www.w3.org/2000/svg";
async function sha256(buf){return[...new Uint8Array(await crypto.subtle.digest("SHA-256",buf))].map(x=>x.toString(16).padStart(2,"0")).join("")}
function setReadiness(key,value,text){readinessState={...readinessState,[key]:value};const row=document.querySelector(`[data-readiness="${key}"]`);if(row){row.className=value.toLowerCase().replaceAll("_","-");const target=$("ready"+key[0].toUpperCase()+key.slice(1));if(target&&text)target.textContent=text}renderReadiness()}
function renderReadiness(){const summary=readinessSummary(readinessState),gate=canStartFieldSession(readinessState,fieldReadinessOverride),card=$("readinessCard");if(!card)return;card.classList.toggle("ready",summary.ready);card.classList.toggle("blocked",summary.blocked.length>0);$("readinessScore").textContent=`${summary.readyCount}/${summary.total}`;$("readinessTitle").textContent=fieldReadinessOverride?"Tryb awaryjny":summary.label;$("readinessMessage").textContent=fieldReadinessOverride?"Kontrola gotowości została świadomie pominięta. GPS lub tryb offline mogą nie działać prawidłowo.":summary.ready?"Telefon jest przygotowany do pracy terenowej. Możesz uruchomić wyprawę.":summary.blocked.length?"Co najmniej jeden wymagany element jest zablokowany. Wykonaj wskazane działania.":"Dokończ krótką kontrolę przed wyjazdem.";$("offlineBadge").classList.toggle("field-ready",summary.ready);const start=$("startBtn");if(start&&session?.state==="READY")start.disabled=!gate.allowed;const override=$("overrideReadinessBtn");if(override)override.hidden=summary.ready}
function readStoredSession(){try{return JSON.parse(localStorage.getItem(STORE))}catch{return null}}
function showRecovery(saved){const status=recoveryStatus(saved,project);if(!status.recoverable)return false;recoveryCandidate=saved;$("recoveryBanner").hidden=false;const when=status.updatedAt?new Date(status.updatedAt).toLocaleString("pl-PL"):"nieznany czas";$("recoveryText").textContent=`Ostatni zapis: ${when}. Bieżący etap zostanie przywrócony.`;return true}
async function checkGpsPermission(){if(!navigator.geolocation){setReadiness("gps","BLOCKED","To urządzenie nie udostępnia geolokalizacji");return}if(navigator.permissions?.query){try{const p=await navigator.permissions.query({name:"geolocation"});setReadiness("gps",permissionStatus(p.state),p.state==="granted"?"Zgoda udzielona":p.state==="denied"?"Lokalizacja zablokowana w ustawieniach przeglądarki":"Naciśnij „Zezwól na GPS”");p.onchange=()=>checkGpsPermission();return}catch{}}setReadiness("gps","ACTION_REQUIRED","Naciśnij „Zezwól na GPS”")}
async function checkOfflineReadiness(){if(!("serviceWorker"in navigator)||!("caches"in window)){setReadiness("offline","BLOCKED","Tryb offline nie jest obsługiwany");return false}try{await navigator.serviceWorker.ready;const cache=await caches.open("malbork-field-readiness");const response=await fetch("release/project.json",{cache:"reload"});if(!response.ok)throw new Error("Brak projektu");await cache.put("field-check-project",response.clone());const cached=await cache.match("field-check-project");if(!cached)throw new Error("Brak zapisu cache");setReadiness("offline","READY","Projekt i aplikacja są dostępne bez Internetu");return true}catch(e){setReadiness("offline","BLOCKED",`Nie udało się przygotować trybu offline: ${e.message}`);return false}}
async function checkStorageReadiness(){if(!navigator.storage){setReadiness("storage","AVAILABLE","Zapis lokalny dostępny; trwałość zależy od systemu");return}try{const persisted=await navigator.storage.persist?.()??false;const estimate=await navigator.storage.estimate();const status=storageStatus({persisted,quota:estimate.quota??0,usage:estimate.usage??0});setReadiness("storage",status,status==="READY"?"System przyznał trwałą pamięć aplikacji":status==="BLOCKED"?"Za mało wolnej pamięci":"Zapis lokalny dostępny; nie usuwaj danych przeglądarki") }catch{setReadiness("storage","AVAILABLE","Zapis lokalny dostępny")}}
function setupInstallInstructions(){$("installSteps").innerHTML=installationInstructions(navigator.userAgent).map(x=>`<li>${x}</li>`).join("");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;readinessState={...readinessState,install:"AVAILABLE"};$("installBtn").disabled=false;$("installBtn").textContent="Zainstaluj aplikację"});window.addEventListener("appinstalled",()=>{$("installBtn").textContent="Aplikacja zainstalowana";$("installBtn").disabled=true;readinessState={...readinessState,install:"READY"}})}
async function loadRelease(){const[m,p,s]=await Promise.all([fetch("release/manifest.json"),fetch("release/project.json"),fetch("release/release-signature.json")]);manifest=await m.json();project=await p.json();const signature=await s.json();const raw=await fetch("release/manifest.json").then(r=>r.arrayBuffer());const hash=await sha256(raw);if(hash!==signature.manifestSha256)throw new Error("Niezgodna suma manifestu");for(const f of manifest.files){const buf=await fetch(`release/${f.path}`).then(r=>{if(!r.ok)throw new Error(`Brak ${f.path}`);return r.arrayBuffer()});if(await sha256(buf)!==f.sha256)throw new Error(`Uszkodzony plik: ${f.path}`)}$("integrityStatus").textContent=`Integralność poprawna · ${manifest.fileCount} plików`;setReadiness("package","READY",`Integralność poprawna · ${manifest.fileCount} plików`);const saved=readStoredSession();session=showRecovery(saved)?initialSession(project):(saved?.projectId===project.metadata.projectId&&saved?.projectVersion===project.metadata.version?saved:initialSession(project));render();await checkGpsPermission();await checkStorageReadiness();await checkOfflineReadiness()}
function restoreSession(){const x=readStoredSession();if(x?.projectId===project.metadata.projectId&&x?.projectVersion===project.metadata.version)return x;return initialSession(project)}
function save(){session.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(session));render()}
function svg(name,attrs={}){const e=document.createElementNS(SVG_NS,name);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e}
function renderMap(){if(!project||!session)return;const pos=lastPosition?{latitude:lastPosition.coords.latitude,longitude:lastPosition.coords.longitude}:null;const model=createMapModel(project,session,pos);const root=$("routeMap");root.replaceChildren();root.append(svg("path",{d:"M 0 365 C 190 320 285 380 430 332 C 600 276 690 254 1000 225 L 1000 405 C 760 418 595 390 430 430 C 250 475 110 440 0 485 Z",class:"map-water"}));root.append(svg("path",{d:"M 315 120 L 500 78 L 610 205 L 455 270 L 325 232 Z",class:"map-landmark"}));const points=model.route.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" ");root.append(svg("polyline",{points,class:"map-route-shadow"}));root.append(svg("polyline",{points,class:"map-route"}));for(const marker of model.markers){const g=svg("g",{class:`map-marker ${marker.state}`,transform:`translate(${marker.point.x} ${marker.point.y})`,tabindex:"0","aria-label":`${marker.displayOrder}. ${marker.name}`});if(marker.state==="active")g.append(svg("circle",{r:26,class:"pulse"}));g.append(svg("circle",{r:25}));const text=svg("text",{x:0,y:1});text.textContent=marker.displayOrder;g.append(text);g.addEventListener("click",()=>{$("mapStatus").textContent=`${marker.displayOrder}. ${marker.name} · ${marker.state==="active"?"punkt aktywny":marker.state==="completed"?"ukończony":marker.state==="skipped"?"pominięty":"zaplanowany"}`});root.append(g)}if(model.user){const g=svg("g",{class:"map-user",transform:`translate(${model.user.x} ${model.user.y})`});g.append(svg("circle",{r:15}));g.append(svg("circle",{r:30}));const label=svg("text",{x:22,y:-18});label.textContent="Ty";g.append(label);root.append(g)}const stage=activeStage(project,session);$("mapStatus").textContent=pos&&stage?`Pozycja GPS zaznaczona · do punktu „${stage.name}”: ${formatDistance(distanceMeters(pos,stage.geometry))}`:stage?`Aktywny punkt: ${stage.displayOrder??"—"}. ${stage.name}`:"Trasa zakończona"}

function pumpSpeech(){if(!audioGuidanceEnabled||speechInProgress||!speechQueueState.active||!("speechSynthesis"in window))return;const item=speechQueueState.active;speechInProgress=true;const u=new SpeechSynthesisUtterance(item.message);u.lang="pl-PL";u.rate=item.kind==="NARRATION"?.96:.98;u.volume=1;const done=()=>{speechInProgress=false;speechQueueState=completeSpeech(speechQueueState);pumpSpeech()};u.onend=done;u.onerror=done;speechSynthesis.speak(u);$("audioGuidanceStatus").textContent=`Odtwarzanie: ${item.message}`}
function queueSpeech(item){if(!audioGuidanceEnabled||!item?.message)return;const previous=speechQueueState.active;const next=enqueueSpeech(speechQueueState,item);const preempt=speechInProgress&&previous&&next.active!==previous&&next.active?.urgent;speechQueueState=next;if(preempt&&"speechSynthesis"in window){speechSynthesis.cancel();speechInProgress=false}pumpSpeech()}
function evaluateNavigationAudio(){const stage=activeStage(project,session);const position=lastPosition?{latitude:lastPosition.coords.latitude,longitude:lastPosition.coords.longitude}:null;if(!stage||!position||session.state!=="ACTIVE")return;const nav=navigationSnapshot(project,session,position,lastStageDistance);const decision=navigationAudioDecision(nav,audioGuidanceState,{stageId:stage.id,awaySamples,minutesToDeadline:minutesUntilDeadline(project,new Date()),returnStageId:project.schedule.emergencyPolicy.returnStageId});audioGuidanceState=decision.state;if(decision.message)queueSpeech(decision)}
function renderNavigation(){const position=lastPosition?{latitude:lastPosition.coords.latitude,longitude:lastPosition.coords.longitude}:null;const nav=navigationSnapshot(project,session,position,lastStageDistance);$("direction").textContent=nav.bearing===null?"—":`${nav.direction} · ${Math.round(nav.bearing)}°`;const alert=$("navigationAlert");alert.hidden=true;alert.className="card navigation-alert";if(nav.offRoute){alert.hidden=false;alert.classList.add("danger");$("navigationAlertTitle").textContent="Poza trasą";$("navigationAlertText").textContent=`Oddalenie od przebiegu trasy: ${formatDistance(nav.routeDistance)}. Wróć w stronę ostatniego odcinka.`}else if(awaySamples>=3){alert.hidden=false;alert.classList.add("warning");$("navigationAlertTitle").textContent="Oddalasz się";$("navigationAlertText").textContent="Odległość do aktywnego punktu rośnie. Sprawdź kierunek marszu."}}
function render(){const stage=activeStage(project,session);$("stageNumber").textContent=stage?.displayOrder??"✓";$("stageCategory").textContent=session.state==="FINISHED"?"Zakończono":stage?.category??"Trasa";$("stageTitle").textContent=session.state==="FINISHED"?"Wyprawa zakończona":stage?.experience.title??"Brak aktywnego punktu";$("stageDescription").textContent=stage?.experience.shortDescription??"";$("instruction").textContent=stage?.experience.instruction??"Wyprawa została zakończona.";$("schedule").textContent=scheduleLabel(stage);$("progress").textContent=`${session.completedStageIds.filter(id=>project.stages.find(s=>s.id===id)?.visibility==="USER").length}/10`;$("distance").textContent=lastPosition&&stage?formatDistance(distanceMeters(lastPosition.coords,stage.geometry)):"—";$("startBtn").textContent=session.state==="READY"?"Rozpocznij wyprawę":"Wyprawa uruchomiona";$("startBtn").disabled=session.state!=="READY";$("manualBtn").disabled=!stage||session.state!=="ACTIVE";$("pauseBtn").textContent=session.state==="PAUSED"?"Wznów":"Wstrzymaj";$("stageList").innerHTML=project.stages.filter(s=>s.visibility==="USER").map(s=>`<li class="${session.completedStageIds.includes(s.id)?"done":session.currentStageId===s.id?"active":""}"><span class="dot">${session.completedStageIds.includes(s.id)?"✓":s.displayOrder}</span><span>${s.name}</span><span class="stage-time">${s.schedule.earliestStart}</span></li>`).join("");renderNavigation();renderMap()}
async function narration(){const stage=activeStage(project,session);const id=stage?.experience.narrationId;if(!id)return;const asset=project.narrations.find(n=>n.id===id);if(!asset)return;const text=await fetch(`release/${asset.textFile}`).then(r=>r.text());queueSpeech({kind:"NARRATION",message:text,priority:AUDIO_PRIORITY.NARRATION,urgent:false})}
function startGps(){if(watchId!==null)return;if(!navigator.geolocation){$("gpsStatus").textContent="GPS niedostępny";return}watchId=navigator.geolocation.watchPosition(pos=>{const stageBefore=activeStage(project,session);const currentDistance=stageBefore?distanceMeters(pos.coords,stageBefore.geometry):null;if(lastStageDistance!==null&&currentDistance!==null&&currentDistance-lastStageDistance>12)awaySamples+=1;else if(currentDistance!==null&&lastStageDistance!==null&&currentDistance<lastStageDistance)awaySamples=0;lastStageDistance=currentDistance;lastPosition=pos;$("gpsStatus").textContent=`Dokładność ±${Math.round(pos.coords.accuracy)} m`;setReadiness("gps","READY",`GPS działa · dokładność ±${Math.round(pos.coords.accuracy)} m`);const stage=activeStage(project,session);if(session.state==="ACTIVE"&&stage?.activation.policy!=="MANUAL"&&pos.coords.accuracy<=stage.activation.maxAccuracyMeters&&distanceMeters(pos.coords,stage.geometry)<=stage.activation.radiusMeters){session=completeCurrent(project,session);lastStageDistance=null;awaySamples=0;save();narration()}else{render();evaluateNavigationAudio()}},err=>{$("gpsStatus").textContent=`Błąd GPS: ${err.message}`;setReadiness("gps",err.code===1?"BLOCKED":"ACTION_REQUIRED",err.code===1?"Lokalizacja zablokowana — zmień zgodę w ustawieniach":"Nie udało się pobrać pozycji — spróbuj ponownie")},{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
$("startBtn").onclick=()=>{const gate=canStartFieldSession(readinessState,fieldReadinessOverride);if(!gate.allowed){alert("Najpierw zakończ kontrolę pakietu, trybu offline i GPS.");return}session.state="ACTIVE";session.startedAt=new Date().toISOString();save();startGps();narration()};$("manualBtn").onclick=()=>{session=completeCurrent(project,session);save();narration()};$("narrateBtn").onclick=narration;$("pauseBtn").onclick=()=>{session.state=session.state==="PAUSED"?"ACTIVE":"PAUSED";save()};$("skipBtn").onclick=()=>{if(confirm("Pominąć bieżący punkt?")){session=skipCurrent(project,session);save()}};$("returnBtn").onclick=()=>{if(confirm("Przejść bezpośrednio do etapu powrotu na dworzec?")){session=beginReturn(project,session);save()}};$("resetBtn").onclick=()=>{if(confirm("Usunąć zapis sesji?")){localStorage.removeItem(STORE);session=initialSession(project);save()}};$("centerMapBtn").onclick=()=>{const card=$("mapFrame").closest(".map-card");card.classList.remove("highlight");requestAnimationFrame(()=>card.classList.add("highlight"));setTimeout(()=>card.classList.remove("highlight"),1200);$("mapFrame").scrollIntoView({behavior:"smooth",block:"center"})};
window.addEventListener("online",()=>{$("offlineBadge").textContent="Online";checkOfflineReadiness()});window.addEventListener("offline",()=>$("offlineBadge").textContent="Offline · gotowa");$("offlineBadge").textContent=navigator.onLine?"Online":"Offline";setupInstallInstructions();renderReadiness();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");loadRelease().catch(e=>{$("integrityStatus").textContent=`Błąd: ${e.message}`;$("integrityCard").style.borderColor="#b22";setReadiness("package","BLOCKED",e.message)});

$("audioGuidanceBtn").onclick=()=>{audioGuidanceEnabled=!audioGuidanceEnabled;$("audioGuidanceBtn").textContent=audioGuidanceEnabled?"Wyłącz prowadzenie głosowe":"Włącz prowadzenie głosowe";$("audioGuidanceStatus").textContent=audioGuidanceEnabled?"Prowadzenie głosowe jest włączone.":"Prowadzenie głosowe jest wyłączone.";if(!audioGuidanceEnabled){speechQueueState=initialSpeechQueueState();speechInProgress=false;if("speechSynthesis"in window)speechSynthesis.cancel()}else pumpSpeech()};

$("overrideReadinessBtn").onclick=()=>{if(confirm("Uruchomić wyprawę mimo nieukończonej kontroli? Może nie działać GPS lub tryb offline.")){fieldReadinessOverride=true;renderReadiness()}};
$("installBtn").onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}else document.querySelector(".install-help").open=true};
$("gpsPermissionBtn").onclick=()=>{if(!navigator.geolocation)return;navigator.geolocation.getCurrentPosition(pos=>{lastPosition=pos;$("gpsStatus").textContent=`Dokładność ±${Math.round(pos.coords.accuracy)} m`;setReadiness("gps","READY",`GPS działa · dokładność ±${Math.round(pos.coords.accuracy)} m`);render()},err=>{setReadiness("gps",err.code===1?"BLOCKED":"ACTION_REQUIRED",err.code===1?"Lokalizacja zablokowana — zmień zgodę w ustawieniach":"Brak pozycji — przejdź pod otwarte niebo i ponów")},{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
$("offlineCheckBtn").onclick=checkOfflineReadiness;
$("audioTestBtn").onclick=()=>{if(!("speechSynthesis"in window)){setReadiness("audio","BLOCKED","Synteza mowy niedostępna");return}const u=new SpeechSynthesisUtterance("Test dźwięku. Prowadzenie głosowe działa poprawnie.");u.lang="pl-PL";u.onend=()=>setReadiness("audio","READY","Głośnik i synteza mowy działają");u.onerror=()=>setReadiness("audio","BLOCKED","Nie udało się odtworzyć testu");speechSynthesis.cancel();speechSynthesis.speak(u)};
$("resumeSessionBtn").onclick=()=>{if(!recoveryCandidate)return;session=recoveryCandidate;recoveryCandidate=null;$("recoveryBanner").hidden=true;save();if(session.state==="ACTIVE")startGps()};
$("discardSessionBtn").onclick=()=>{localStorage.removeItem(STORE);recoveryCandidate=null;session=initialSession(project);$("recoveryBanner").hidden=true;save()};
