export function distanceMeters(a,b){const R=6371000;const r=x=>x*Math.PI/180;const dLat=r(b.latitude-a.latitude),dLon=r(b.longitude-a.longitude);const h=Math.sin(dLat/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
export function formatDistance(m){if(!Number.isFinite(m))return "—";return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`}
export function initialSession(project){const start=project.route.startStageId;return{projectId:project.metadata.projectId,projectVersion:project.metadata.version,state:"READY",currentStageId:start,completedStageIds:[],skippedStageIds:[],visitCounts:{},decisions:[],startedAt:null,updatedAt:new Date().toISOString()}}
export function nextStage(project,session){const current=project.stages.find(s=>s.id===session.currentStageId);return current?.navigation.nextStageId??null}
export function completeCurrent(project,session){const id=session.currentStageId;if(!id)return session;const completed=[...new Set([...session.completedStageIds,id])];const next=nextStage(project,session);return{...session,completedStageIds:completed,currentStageId:next,state:next?"ACTIVE":"FINISHED",updatedAt:new Date().toISOString()}}
export function skipCurrent(project,session){const id=session.currentStageId;if(!id)return session;const next=nextStage(project,session);return{...session,skippedStageIds:[...new Set([...session.skippedStageIds,id])],currentStageId:next,state:next?"ACTIVE":"FINISHED",decisions:[...session.decisions,{type:"SKIP",stageId:id,at:new Date().toISOString()}],updatedAt:new Date().toISOString()}}
export function beginReturn(project,session){const target=project.schedule.emergencyPolicy.returnStageId;const remaining=project.stages.filter(s=>s.visibility==="USER"&&!session.completedStageIds.includes(s.id)&&s.id!==target).map(s=>s.id);return{...session,currentStageId:target,state:"ACTIVE",skippedStageIds:[...new Set([...session.skippedStageIds,...remaining])],decisions:[...session.decisions,{type:"BEGIN_RETURN",fromStageId:session.currentStageId,at:new Date().toISOString()}],updatedAt:new Date().toISOString()}}
export function activeStage(project,session){return project.stages.find(s=>s.id===session.currentStageId)??null}
export function scheduleLabel(stage){if(!stage?.schedule)return"—";return`${stage.schedule.earliestStart}–${stage.schedule.latestEnd}`}
export function mapStages(project){return project.stages.filter(s=>s.visibility==="USER")}
export function mapBounds(stages,padding=.12){if(!stages.length)return{minLatitude:0,maxLatitude:1,minLongitude:0,maxLongitude:1};const lats=stages.map(s=>s.geometry.latitude),lons=stages.map(s=>s.geometry.longitude);let minLatitude=Math.min(...lats),maxLatitude=Math.max(...lats),minLongitude=Math.min(...lons),maxLongitude=Math.max(...lons);const latSpan=Math.max(maxLatitude-minLatitude,.0005),lonSpan=Math.max(maxLongitude-minLongitude,.0005);minLatitude-=latSpan*padding;maxLatitude+=latSpan*padding;minLongitude-=lonSpan*padding;maxLongitude+=lonSpan*padding;return{minLatitude,maxLatitude,minLongitude,maxLongitude}}
export function projectCoordinate(coordinate,bounds,width=1000,height=640){const lonSpan=bounds.maxLongitude-bounds.minLongitude||1,latSpan=bounds.maxLatitude-bounds.minLatitude||1;return{x:(coordinate.longitude-bounds.minLongitude)/lonSpan*width,y:(bounds.maxLatitude-coordinate.latitude)/latSpan*height}}
export function markerState(stage,session){if(session.completedStageIds.includes(stage.id))return"completed";if(session.skippedStageIds.includes(stage.id))return"skipped";if(session.currentStageId===stage.id)return"active";return"pending"}
export function createMapModel(project,session,position=null,width=1000,height=640){const stages=mapStages(project),bounds=mapBounds(stages);const markers=stages.map(stage=>({...stage,point:projectCoordinate(stage.geometry,bounds,width,height),state:markerState(stage,session)}));const route=markers.map(m=>m.point);const user=position?projectCoordinate(position,bounds,width,height):null;return{bounds,width,height,markers,route,user}}

export function bearingDegrees(a,b){const r=x=>x*Math.PI/180;const dLon=r(b.longitude-a.longitude);const lat1=r(a.latitude),lat2=r(b.latitude);const y=Math.sin(dLon)*Math.cos(lat2);const x=Math.cos(lat1)*Math.sin(lat2)-Math.sin(lat1)*Math.cos(lat2)*Math.cos(dLon);return(Math.atan2(y,x)*180/Math.PI+360)%360}
export function compassDirection(degrees){const dirs=["N","NE","E","SE","S","SW","W","NW"];return dirs[Math.round(((degrees%360)+360)%360/45)%8]}
function localMeters(origin,p){const latScale=111320;const lonScale=111320*Math.cos(origin.latitude*Math.PI/180);return{x:(p.longitude-origin.longitude)*lonScale,y:(p.latitude-origin.latitude)*latScale}}
export function distanceToSegmentMeters(point,a,b){const pa=localMeters(a,point),ba=localMeters(a,b);const len=ba.x*ba.x+ba.y*ba.y;if(len===0)return Math.hypot(pa.x,pa.y);const t=Math.max(0,Math.min(1,(pa.x*ba.x+pa.y*ba.y)/len));return Math.hypot(pa.x-ba.x*t,pa.y-ba.y*t)}
export function distanceToRouteMeters(project,position){const stages=mapStages(project);if(stages.length<2)return stages[0]?distanceMeters(position,stages[0].geometry):Infinity;let best=Infinity;for(let i=0;i<stages.length-1;i++)best=Math.min(best,distanceToSegmentMeters(position,stages[i].geometry,stages[i+1].geometry));return best}
export function navigationSnapshot(project,session,position,previousDistance=null){const stage=activeStage(project,session);if(!stage||!position)return{distance:null,bearing:null,direction:"—",routeDistance:null,trend:"UNKNOWN",offRoute:false};const distance=distanceMeters(position,stage.geometry);const bearing=bearingDegrees(position,stage.geometry);const routeDistance=distanceToRouteMeters(project,position);let trend="STABLE";if(Number.isFinite(previousDistance)){const delta=distance-previousDistance;trend=delta>12?"AWAY":delta<-8?"CLOSER":"STABLE"}return{distance,bearing,direction:compassDirection(bearing),routeDistance,trend,offRoute:routeDistance>120}}

export const AUDIO_PRIORITY={NARRATION:10,PROXIMITY:20,DIRECTION:30,MOVING_AWAY:50,OFF_ROUTE:80,CRITICAL_RETURN:100};
export function initialAudioGuidanceState(){return{lastStageId:null,lastDirection:null,lastDirectionAt:0,lastAwayAt:0,lastOffRouteAt:0,lastCriticalReturnAt:0,proximityStageIds:[]}}
export function minutesUntilDeadline(project,now=new Date()){const date=project?.schedule?.date,clock=project?.schedule?.mustBeInTrainBy;if(!date||!clock)return null;const [h,m]=clock.split(":").map(Number);const deadline=new Date(`${date}T${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:00`);return Math.ceil((deadline.getTime()-now.getTime())/60000)}
export function navigationAudioDecision(nav,state,context,nowMs=Date.now()){
 const next={...state,proximityStageIds:[...(state.proximityStageIds??[])]};
 const stageId=context?.stageId??null,awaySamples=context?.awaySamples??0,minDirectionDistance=context?.minDirectionDistance??35,proximityDistance=context?.proximityDistance??80,minutesToDeadline=context?.minutesToDeadline??null,returnStageId=context?.returnStageId??null;
 if(Number.isFinite(minutesToDeadline)&&minutesToDeadline<=30&&stageId&&stageId!==returnStageId){const due=nowMs-next.lastCriticalReturnAt>=300000||next.lastCriticalReturnAt===0;if(due){next.lastCriticalReturnAt=nowMs;return{kind:"CRITICAL_RETURN",priority:AUDIO_PRIORITY.CRITICAL_RETURN,urgent:true,message:`Pozostało ${Math.max(0,minutesToDeadline)} minut do obowiązkowego czasu wejścia do pociągu. Rozpocznij bezpośredni powrót na dworzec.`,state:next}}return{kind:null,priority:0,urgent:false,message:null,state:next}}
 if(nav.offRoute){const due=nowMs-next.lastOffRouteAt>=120000||next.lastOffRouteAt===0;if(due){next.lastOffRouteAt=nowMs;next.lastStageId=stageId;next.lastDirection=nav.direction;return{kind:"OFF_ROUTE",priority:AUDIO_PRIORITY.OFF_ROUTE,urgent:true,message:`Zszedłeś z trasy. Oddalenie wynosi ${formatDistance(nav.routeDistance)}. Wróć w stronę ostatniego odcinka.`,state:next}}return{kind:null,priority:0,urgent:false,message:null,state:next}}
 if(awaySamples>=3){const due=nowMs-next.lastAwayAt>=90000||next.lastAwayAt===0;if(due){next.lastAwayAt=nowMs;next.lastStageId=stageId;next.lastDirection=nav.direction;return{kind:"MOVING_AWAY",priority:AUDIO_PRIORITY.MOVING_AWAY,urgent:false,message:"Oddalasz się od aktywnego punktu. Sprawdź kierunek marszu.",state:next}}return{kind:null,priority:0,urgent:false,message:null,state:next}}
 if(nav.distance!==null&&nav.distance<=proximityDistance&&stageId){if(!next.proximityStageIds.includes(stageId)){next.proximityStageIds.push(stageId);next.lastStageId=stageId;return{kind:"PROXIMITY",priority:AUDIO_PRIORITY.PROXIMITY,urgent:false,message:`Zbliżasz się do punktu. Pozostało ${formatDistance(nav.distance)}.`,state:next}}return{kind:null,priority:0,urgent:false,message:null,state:next}}
 if(nav.distance===null||nav.bearing===null||nav.distance<minDirectionDistance)return{kind:null,priority:0,urgent:false,message:null,state:next};
 const stageChanged=stageId!==next.lastStageId,directionChanged=nav.direction!==next.lastDirection,directionDue=nowMs-next.lastDirectionAt>=75000||next.lastDirectionAt===0;
 if(stageChanged||(directionChanged&&directionDue)){next.lastStageId=stageId;next.lastDirection=nav.direction;next.lastDirectionAt=nowMs;return{kind:"DIRECTION",priority:AUDIO_PRIORITY.DIRECTION,urgent:false,message:`Kieruj się na ${nav.direction}. Do punktu pozostało ${formatDistance(nav.distance)}.`,state:next}}
 next.lastStageId=stageId;return{kind:null,priority:0,urgent:false,message:null,state:next}
}
export function initialSpeechQueueState(){return{active:null,queue:[]}}
export function enqueueSpeech(state,item){if(!item?.message)return state;const normalized={kind:item.kind??"NARRATION",message:item.message,priority:item.priority??AUDIO_PRIORITY.NARRATION,urgent:Boolean(item.urgent)};let active=state.active,queue=[...state.queue];if(!active)return{active:normalized,queue};if(normalized.urgent&&normalized.priority>active.priority)return{active:normalized,queue:queue.filter(x=>x.priority>=normalized.priority)};const duplicate=[active,...queue].some(x=>x.kind===normalized.kind&&x.message===normalized.message);if(!duplicate){queue.push(normalized);queue.sort((a,b)=>b.priority-a.priority)}return{active,queue}}
export function completeSpeech(state){if(!state.active)return state;const [active=null,...queue]=state.queue;return{active,queue}}
